sudo: required
dist: trusty
os:
  - "linux"
  - "osx"
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -y qtbase5-dev python3-pyqt5 python3-pip; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export PATH=/usr/bin:$PATH; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then python2 -m pip install --upgrade pip; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo python3 -m pip install --upgrade pip; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo python3 -m pip install tox coveralls; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo make pyqt; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install python3; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install pyqt5; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew link --force qt5; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=/usr/local/bin:$PATH; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python2 -m pip install --upgrade pip; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python3 -m pip install --upgrade pip; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python3 -m pip install tox coveralls; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then make pyqt; fi
before_script:
  - env
  - which python && python --version
  - which python2 && python2 --version
  - which python3 && python3 --version
  - which tox && tox --version
script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then tox -e py27,py34,py35,flake8,pylint; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then tox -e py35,flake8; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then make frozen-tahoe; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Tahoe-LAFS/tahoe --version-and-path; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then make dmg; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Tahoe-GUI.app/Contents/MacOS/Tahoe-GUI --version; fi
after_success:
  - coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-gui"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"
